from turtle import *

print("andria kirkitadze") 

width(7)

color("blue")



forward(170)
left(90)
forward(170)
left(90)
forward(170)
left(90)
forward(170)
left(90)
forward(70)
left(90)
color("brown")
forward(90)

forward(40)
left(90)
forward(40)
left(90)
forward(40)
left(90)

forward(90)
right(90)
forward(90)

penup()
goto(170,170)
pendown()
color("red")
begin_fill()
right(140)
forward(120)
left(95)
forward(130)
end_fill()


penup()
goto(0,0)
pendown()
color("green")
begin_fill()
right(40)
forward(337)
left(85)
forward(250)
left(90)
forward(660)
left(90)
forward(280)
left(90)
forward(320)
end_fill()



exitonclick()